name: Lint GitHub workflows with zizmor

run-name: 'Lint GitHub workflows with zizmor - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}'

on:
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  zizmor:
    name: Run zizmor latest via PyPI
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ GitHub checkout branch "${{ github.head_ref }}"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: â¬‡ï¸ Install the latest version of uv
        uses: astral-sh/setup-uv@v4
      - name: ğŸ” Run zizmor
        run: uvx zizmor .github/workflows --format plain --offline --min-confidence low --min-severity low
